<a href="https://colab.research.google.com/github/aholanda/edu-calculo-numerico/blob/main/sistemas_lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Equações Lineares

## Eliminaçao Gaussiana

Consideramos o sistema de equações a seguir com $3$ variáveis:

$$\displaylines{
  3x-4y+z=1\cr
  2x+y+2z=3\cr
  x+2y-z=5
  }$$
Primeiro, dividimos a primeira equação por $3$

  $$\eqalignno{x-\frac{4}{3}y+\frac{1}{3}z=\frac{1}{3}&(1)}$$

então subtraímos 2 vezes a Eq. (1) da segunda equação e 1 vez da terceira equação para eliminar o $x$ destas equações, obtendo

$$\eqalign{
    x+\frac{4}{3}y+\frac{1}{3}z=\frac{1}{3}\cr
    \frac{11}{3}y+\frac{4}{3}z=\frac{7}{3}\cr
    \frac{10}{3}y-\frac{4}{3}z=\frac{14}{3}\cr
}$$

em seguida, dividimos a segunda equação por $\frac{11}{3}$

$$\eqalign{y+\frac{4}{11}z=\frac{7}{11}&(2)}$$

e multiplicamos a Eq. (2) por $\frac{10}{3}$ para subtrairmos da terceira equação obtendo

$$-\frac{84}{33}z=\frac{84}{33}.$$

Então

$$z=-1$$

e substituímos $z$ na Eq. (2) obtendo

$$y=\frac{11}{4}-\frac{4}{11}z=1$$

e substituímos $y$ e $z$ na Eq. (1) obtendo

$$x=\frac{1}{3}+\frac{4}{3}y-\frac{1}{3}z=\frac{1}{2}\frac{4}{3}+\frac{1}{3}=2.$$

Para generalizar este processo, consideramos $n$ equações de $n$ variáveis

$$\eqalign{
  a_{1,1}x_1+a_{1,2}x_2+a_{1,3}x_3+\ldots+a_{1,n}x_n-b_1\cr
  a_{2,1}x_1+a_{2,2}x_2+a_{2,3}x_3+\ldots+a_{2,n}x_n-b_2\cr
  \vdots\cr
  a_{n,1}x_1+a_{n,2}x_2+a_{n,3}x_3+\ldots+a_{n,n}x_n-b_n
}$$

de forma a obter um algoritmo para a eliminação de Gauss

```
dividir equação 1 por a[1,1]
para i=2:n:
    subtrair a[i,i-1] vezes a equação i-1 da equação i

para i=n,1:
  calcular x[i,i] na equação i
```

Na primeira passada o custo é $n-1$ e na segunda $n$, 
portanto o desempenho do algoritmo é $O(n)$.

### Exercícios

1. Resolva usando a eliminação de Gauss.

a. 
$$\eqalign{
x+y=15\cr
4x+2y=48
}$$

b.
$$\eqalign{
x+y+z=2\cr
4x+4y+2z=2\cr
2x+y-z=0
}$$

c.
$$\eqalign{
2x_1 & -1x_2 & +3x_3 & +5x_4 &=& -7\cr
2x_1 & +1x_2 & +4x_3 & -2x_4 &=& -18\cr
3x_1 &       & +3x_3 & -4x_4 &=& -25\cr
     & -2x_2 &       & +6x_4 &= &-24
}$$



### Biblioteca `numpy.linalg`

Podemos usar a função `solve` da biblioteca (pacote) `numpy.linalg` para resover o sistema de equações lineares da seguinte maneira:

In [ ]:
import numpy as np

a = np.array([[3, -4, 1], [2, 1, 2], [1, 2, -1]])
b = np.array([1, 3, 5])
x = np.linalg.solve(a, b)
print(x)

[ 2.  1. -1.]


## Fatoração LU

A fatoração (decomposição) LU de uma matrix $N\times N$ chamada $A$ gera uma matriz triangular inferior $L$ e uma matriz triangular superior $U$

$$\eqalign{
    Ax=b& ⇒\cr
   (LU)x = b&\Rightarrow\cr
   L(Ux) = b&\Rightarrow \cr
   Ly = b \qquad& e\qquad Ux=y
}$$

Exemplo [copiado do [livro da UFRGS](https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/sdsl-fatoracao_lu.html)]:

\begin{align}
\begin{pmatrix}
 1 & 1 & 1 \\
 2 & 1 & -1  \\
 2 & -1 & 1
 \end{pmatrix}
 \begin{pmatrix} 
  x_1\\ x_2\\ x_3
 \end{pmatrix}
 = 
 \begin{pmatrix} 
  -2\\ 1\\ 3
 \end{pmatrix}
\end{align} 

Usando a Eq. (1) para decompor a matrix $A$, obtemos $LU$

\begin{align}
\begin{bmatrix}
 1 & 1 & 1 \\
 2 & 1 & -1  \\
 2 & -1 & 1
 \end{bmatrix}=&
 \begin{bmatrix} 
 1 & 0 & 0 \\
 0 & 1 & 0 \\
 0 & 0 & 1
 \end{bmatrix}
 \begin{bmatrix} 
  1 & 1 & 1 \\
  2 & 1& -1 \\ 
  2 & -1 & 1
 \end{bmatrix}\\
 =&\begin{bmatrix} 
 1 & 0 & 0 \\
 2 & 1 & 0 \\
 2 & 0 & 1
 \end{bmatrix}
 \begin{bmatrix} 
  1 & 1 & 1 \\
  0 & -1& -3 \\ 
  0 & -3 & -1
 \end{bmatrix}\\
 =&\begin{bmatrix} 
 1 & 0 & 0 \\
 2 & 1 & 0 \\
 2 & 3 & 1
 \end{bmatrix}
 \begin{bmatrix} 
  1 & 1 & 1 \\
  0 & -1& -3 \\ 
  0 & 0 & 8
 \end{bmatrix}
\end{align} 

Resolvemos $Ly=b$
$$\eqalign{
  y_1  &       &      &=-2\cr
  2y_1 & +y_2  &      &=1\cr
  2y_1 & +3y_2 & +y_3 &=3
  }$$

onde obtemos $y_=-2,y_2=-5, y_3=-8$; e então $Ux=y$

$$\eqalign{
   x_1 & +x_2 & +x_3    &=-2\cr
       & -x_2 & -3x_3   &=5\cr
       &      & +8x_3    &=-8
  }$$

obtendo a solução $x_3=-1$, $x_2=-2$, $x_1=1$.


In [10]:
import numpy as np

def LU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)  
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    return L, U
A = [[1, 1, 1], 
     [2, 1, -1], 
     [2, -1, 1]]
L, U = LU(A)
print('L=\n', L)
print('U=\n', U)

L=
 [[1. 0. 0.]
 [2. 1. 0.]
 [2. 3. 1.]]
U=
 [[ 1  1  1]
 [ 0 -1 -3]
 [ 0  0  8]]


# Biblioteca `scipy.linalg`

Mostramos a seguir o uso da função `lu` da biblioteca (pacote) `scipy.linalg` para a fatoração $LU$:

In [ ]:
import numpy as np
import scipy
import numpy.linalg

A = np.array([[3, -4, 1], [2, 1, 2], [1, 2, -1]])
b = np.array([1, 3, 5])
P, L, U = scipy.linalg.lu(A)
print('A =\n', A)
print('L =\n', L)
print('U =\n', U)

x = numpy.linalg.solve(A, b)
print(x)

A =
 [[ 3 -4  1]
 [ 2  1  2]
 [ 1  2 -1]]
L =
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.90909091 1.        ]]
U =
 [[ 3.         -4.          1.        ]
 [ 0.          3.66666667  1.33333333]
 [ 0.          0.         -2.54545455]]
[ 2.  1. -1.]


## Referência

- Numerical Methods for Scientists and Engineers. Richard Hamming. Dover Publications; 2nd revised edition, 1987.